import { ApiError, audit, bucket, database, id, int, isoDate, jsonError, month, now, one, requireOwner, requirePermission, rows, safeJson, str } from "../_lib";
import { calculateMonthlyRent } from "../../rent-calculations";
import { rolePermissions, type WorkspaceRole } from "../../permissions";
import type { BulkRowResult, OperationsAction } from "../../operations-contracts";

export const dynamic = "force-dynamic";

type Row = Record<string, any>;

export async function GET(request: Request) {
  try {
    const owner = await requireOwner();
    const db = database();
    const url = new URL(request.url);
    const billingMonth = month(url.searchParams.get("month") || currentMonth());
    const propertyId = str(url.searchParams.get("propertyId"), "Property");
    if (propertyId) await owned(db, "properties", propertyId, owner.key);
    const page = Math.max(1, Number(url.searchParams.get("page") || 1));
    const pageSize = Math.min(100, Math.max(10, Number(url.searchParams.get("pageSize") || 30)));
    const offset = (page - 1) * pageSize;
    const [checklist, closing, templates, communications, bankTransactions, paymentRequests, inspections, inspectionItems, renewals, invitations, members, onboarding, subscriptions, plans, backups] = await Promise.all([
      monthlyChecklist(db, owner.key, billingMonth, propertyId),
      one(db.prepare("SELECT * FROM monthly_closings WHERE owner_key=? AND billing_month=? AND ((property_id IS NULL AND ?='') OR property_id=?) LIMIT 1").bind(owner.key, billingMonth, propertyId, propertyId)),
      rows(db.prepare("SELECT * FROM communication_templates WHERE owner_key=? AND active=1 ORDER BY kind").bind(owner.key)),
      rows(db.prepare("SELECT * FROM communication_events WHERE owner_key=? ORDER BY created_at DESC LIMIT ? OFFSET ?").bind(owner.key, pageSize, offset)),
      bankInbox(db, owner.key, pageSize, offset),
      rows(db.prepare("SELECT * FROM payment_requests WHERE owner_key=? ORDER BY created_at DESC LIMIT ? OFFSET ?").bind(owner.key, pageSize, offset)),
      rows(db.prepare("SELECT * FROM inspections WHERE owner_key=? ORDER BY inspection_date DESC, created_at DESC LIMIT ? OFFSET ?").bind(owner.key, pageSize, offset)),
      rows(db.prepare("SELECT * FROM inspection_items WHERE owner_key=? ORDER BY created_at").bind(owner.key)),
      rows(db.prepare("SELECT * FROM lease_renewals WHERE owner_key=? ORDER BY created_at DESC LIMIT ? OFFSET ?").bind(owner.key, pageSize, offset)),
      rows(db.prepare("SELECT id,email,role,status,expires_at,accepted_at,created_at FROM workspace_invitations WHERE owner_key=? ORDER BY created_at DESC").bind(owner.key)),
      rows(db.prepare("SELECT wm.id,wm.user_id,wm.role,wm.status,wm.created_at,u.email,u.display_name FROM workspace_memberships wm JOIN users u ON u.id=wm.user_id WHERE wm.workspace_id=? ORDER BY CASE wm.role WHEN 'owner' THEN 0 ELSE 1 END,u.display_name").bind(owner.key)),
      one(db.prepare("SELECT * FROM onboarding_progress WHERE owner_key=?").bind(owner.key)),
      one(db.prepare("SELECT * FROM workspace_subscriptions WHERE owner_key=?").bind(owner.key)),
      rows(db.prepare("SELECT sp.* FROM subscription_plans sp JOIN workspace_subscriptions ws ON ws.plan_id=sp.id WHERE ws.owner_key=? AND sp.active=1 ORDER BY sp.room_limit").bind(owner.key)),
      rows(db.prepare("SELECT * FROM backup_snapshots WHERE owner_key=? ORDER BY created_at DESC LIMIT 20").bind(owner.key)),
    ]);
    const roomCount = await one<{ count: number }>(db.prepare("SELECT COUNT(*) count FROM rooms WHERE owner_key=? AND active=1").bind(owner.key));
    return Response.json({
      month: billingMonth, propertyId, role: owner.role, permissions: rolePermissions[owner.role], checklist, closing,
      templates, communications, bankTransactions, paymentRequests, inspections, inspectionItems, renewals, invitations, members,
      onboarding: onboarding ?? { current_step: 1, completed_steps_json: "[]" }, subscription: subscriptions, plans, backups,
      usage: { activeRooms: Number(roomCount?.count || 0) }, pagination: { page, pageSize }, integrations: { email: "not_configured", whatsappProvider: "not_configured", paymentProvider: "not_configured" },
    });
  } catch (error) { return jsonError(error); }
}

export async function POST(request: Request) {
  let claim: { ownerKey: string; requestKey: string } | null = null;
  try {
    const owner = await requireOwner();
    const db = database();
    const body = safeJson(await request.json());
    const action = str(body.action, "Action", true) as OperationsAction;
    const requestKey = str(body.requestKey, "Request key", true);
    const payload = safeJson(body.payload);
    authorize(owner.role, action, owner);
    const cached = await one<{ response_json: string }>(db.prepare("SELECT response_json FROM operation_requests WHERE owner_key=? AND request_key=? AND action=?").bind(owner.key, requestKey, action));
    if (cached) return Response.json({ ok: true, repeated: true, result: JSON.parse(cached.response_json) });
    const claimed = await db.prepare("INSERT OR IGNORE INTO operation_requests (id,owner_key,request_key,action,response_json,completed_at,created_at) VALUES (?,?,?,?, '{}','',?)").bind(id("op"), owner.key, requestKey, action, now()).run();
    if (!claimed.meta.changes) throw new ApiError(409, "This operation is already being processed. Retry with the same request shortly.");
    claim = { ownerKey: owner.key, requestKey };

    let result: unknown;
    switch (action) {
      case "set_monthly_close": result = await setMonthlyClose(db, owner, payload); break;
      case "bulk_generate_rent": result = await bulkGenerateRent(db, owner, payload); break;
      case "bulk_finalize_electricity": result = await bulkFinalizeElectricity(db, owner, payload); break;
      case "save_communication_template": result = await saveTemplate(db, owner, payload); break;
      case "prepare_communication": result = await prepareCommunication(db, owner, payload); break;
      case "set_communication_preference": result = await setCommunicationPreference(db, owner, payload); break;
      case "import_bank_transactions": result = await importBankTransactions(db, owner, payload); break;
      case "reconcile_bank_transaction": result = await reconcileBankTransaction(db, owner, payload); break;
      case "undo_bank_reconciliation": result = await undoBankReconciliation(db, owner, payload); break;
      case "create_payment_request": result = await createPaymentRequest(db, owner, payload, requestKey); break;
      case "confirm_payment_request": result = await confirmPaymentRequest(db, owner, payload); break;
      case "create_inspection": result = await createInspection(db, owner, payload); break;
      case "finalize_inspection": result = await finalizeInspection(db, owner, payload); break;
      case "create_renewal": result = await createRenewal(db, owner, payload); break;
      case "set_renewal_status": result = await setRenewalStatus(db, owner, payload); break;
      case "update_onboarding": result = await updateOnboarding(db, owner, payload); break;
      case "create_workspace_invitation": result = await createInvitation(db, owner, payload); break;
      case "revoke_workspace_invitation": result = await revokeInvitation(db, owner, payload); break;
      case "accept_workspace_invitation": result = await acceptInvitation(db, owner, payload); break;
      case "set_member_role": result = await setMemberRole(db, owner, payload); break;
      case "revoke_member": result = await revokeMember(db, owner, payload); break;
      case "configure_test_plan": result = await configureTestPlan(db, owner, payload); break;
      case "create_backup": result = await createBackup(db, owner, payload); break;
      default: throw new ApiError(400, "Unsupported operations action.");
    }
    const responseJson = JSON.stringify(result);
    await db.prepare("UPDATE operation_requests SET response_json=?,completed_at=? WHERE owner_key=? AND request_key=?").bind(responseJson, now(), owner.key, requestKey).run();
    return Response.json({ ok: true, result });
  } catch (error) {
    if (claim) { try { await database().prepare("DELETE FROM operation_requests WHERE owner_key=? AND request_key=? AND completed_at='' ").bind(claim.ownerKey, claim.requestKey).run(); } catch {} }
    return jsonError(error);
  }
}

function authorize(role: WorkspaceRole, action: OperationsAction, owner: Awaited<ReturnType<typeof requireOwner>>) {
  const permission = action === "set_monthly_close" ? "period.close"
    : action.includes("invitation") || action.includes("member") ? "members.manage"
    : action.includes("communication") ? "communications.write"
    : action.includes("inspection") || action.includes("renewal") || action === "update_onboarding" ? "records.write"
    : action === "create_backup" || action === "configure_test_plan" ? "security.manage"
    : "finance.write";
  if (action === "accept_workspace_invitation") return;
  requirePermission(owner, permission);
}

async function monthlyChecklist(db: D1Database, ownerKey: string, billingMonth: string, propertyId: string) {
  const start = `${billingMonth}-01`; const end = monthEnd(billingMonth); const propertyClause = propertyId ? " AND t.property_id=?" : ""; const bind = (...values: unknown[]) => propertyId ? [...values, propertyId] : values;
  const [tenancies, rates, rentCharges, readings, bills, payments, allocations, overdue, deposits, expenses, maintenance] = await Promise.all([
    rows<Row>(db.prepare(`SELECT t.* FROM tenancies t WHERE t.owner_key=? AND t.rent_start_date<=? AND (t.move_out_date IS NULL OR t.move_out_date>=?)${propertyClause}`).bind(...bind(ownerKey, end, start))),
    rows<Row>(db.prepare("SELECT * FROM rent_rate_history WHERE owner_key=? AND effective_from<=? ORDER BY effective_from").bind(ownerKey, end)),
    rows<Row>(db.prepare(`SELECT r.* FROM rent_charges r JOIN tenancies t ON t.id=r.tenancy_id WHERE r.owner_key=? AND r.billing_month=? AND r.reversed=0${propertyClause}`).bind(...bind(ownerKey, billingMonth))),
    rows<Row>(db.prepare(`SELECT e.* FROM electricity_readings e JOIN tenancies t ON t.id=e.tenancy_id WHERE e.owner_key=? AND e.billing_month=?${propertyClause}`).bind(...bind(ownerKey, billingMonth))),
    rows<Row>(db.prepare(`SELECT e.* FROM electricity_bills e JOIN tenancies t ON t.id=e.tenancy_id WHERE e.owner_key=? AND e.billing_month=? AND e.reversed=0${propertyClause}`).bind(...bind(ownerKey, billingMonth))),
    rows<Row>(db.prepare(`SELECT p.* FROM payments p JOIN tenancies t ON t.id=p.tenancy_id WHERE p.owner_key=? AND p.status='recorded'${propertyClause}`).bind(...bind(ownerKey))),
    rows<Row>(db.prepare("SELECT * FROM payment_allocations WHERE owner_key=? AND reversed=0").bind(ownerKey)),
    one<{ count: number; amount: number }>(db.prepare(`SELECT COUNT(*) count,COALESCE(SUM(c.amount-COALESCE(a.paid,0)),0) amount FROM (SELECT r.id,r.tenancy_id,r.amount_paise amount,r.due_date FROM rent_charges r WHERE r.owner_key=? AND r.reversed=0 UNION ALL SELECT e.id,e.tenancy_id,e.total_paise,COALESCE(e.due_date,e.billing_month||'-28') FROM electricity_bills e WHERE e.owner_key=? AND e.reversed=0 UNION ALL SELECT o.id,o.tenancy_id,o.amount_paise,o.charge_date FROM other_charges o WHERE o.owner_key=? AND o.reversed=0 AND o.amount_paise>0) c JOIN tenancies t ON t.id=c.tenancy_id LEFT JOIN (SELECT charge_id,SUM(amount_paise) paid FROM payment_allocations WHERE owner_key=? AND reversed=0 GROUP BY charge_id) a ON a.charge_id=c.id WHERE c.due_date<? AND c.amount-COALESCE(a.paid,0)>0${propertyClause}`).bind(...bind(ownerKey, ownerKey, ownerKey, ownerKey, today()))),
    one<{ count: number }>(db.prepare(`SELECT COUNT(*) count FROM deposit_ledger d JOIN tenancies t ON t.id=d.tenancy_id WHERE d.owner_key=? AND d.date BETWEEN ? AND ? AND d.type IN ('adjustment','deduction','refund','refund_due')${propertyClause}`).bind(...bind(ownerKey, start, end))),
    one<{ count: number; amount: number }>(db.prepare(`SELECT COUNT(*) count,COALESCE(SUM(e.amount_paise),0) amount FROM expenses e WHERE e.owner_key=? AND e.payment_status='unpaid' AND e.incurred_date<=?${propertyId ? " AND e.property_id=?" : ""}`).bind(...(propertyId ? [ownerKey, end, propertyId] : [ownerKey, end]))),
    one<{ count: number }>(db.prepare(`SELECT COUNT(*) count FROM maintenance_issues m WHERE m.owner_key=? AND m.status NOT IN ('completed','cancelled')${propertyId ? " AND m.property_id=?" : ""}`).bind(...(propertyId ? [ownerKey, propertyId] : [ownerKey]))),
  ]);
  const expectedRentPaise = tenancies.reduce((sum, tenancy) => sum + (calculateMonthlyRent(tenancy, rates, billingMonth)?.amountPaise || 0), 0);
  const billedRentPaise = rentCharges.reduce((sum, charge) => sum + Number(charge.amount_paise), 0);
  const allocatedByPayment = new Map<string, number>(); allocations.forEach((allocation) => allocatedByPayment.set(allocation.payment_id, (allocatedByPayment.get(allocation.payment_id) || 0) + Number(allocation.amount_paise)));
  const unappliedPayments = payments.map((payment) => Math.max(0, Number(payment.amount_paise) - (allocatedByPayment.get(payment.id) || 0))).filter((amount) => amount > 0);
  const issues = [
    issue("rent_missing", "blocking", "Rent charges not fully generated", Math.max(0, tenancies.length - rentCharges.length), Math.max(0, expectedRentPaise - billedRentPaise), "Preview and generate only the missing contractual rent charges.", "rent"),
    issue("meter_missing", "blocking", "Meter readings missing", Math.max(0, tenancies.length - readings.length), undefined, "Enter readings for occupied rooms or record an authorized exception.", "electricity"),
    issue("electricity_draft", "blocking", "Electricity bills unfinished", readings.filter((reading) => reading.status !== "finalized").length + Math.max(0, readings.length - bills.length), undefined, "Review readings and finalize each saved bill.", "electricity"),
    issue("unapplied", "warning", "Payments waiting for allocation", unappliedPayments.length, unappliedPayments.reduce((sum, amount) => sum + amount, 0), "Allocate existing tenant credit without recording cash again.", "payments"),
    issue("overdue", "warning", "Overdue balances need follow-up", Number(overdue?.count || 0), Number(overdue?.amount || 0), "Open the exact tenant balances and prepare follow-ups.", "reports"),
    issue("deposits", "warning", "Deposit movements need review", Number(deposits?.count || 0), undefined, "Verify deductions, refund obligations and actual refund payments.", "payments"),
    issue("expenses", "warning", "Expenses remain unpaid", Number(expenses?.count || 0), Number(expenses?.amount || 0), "Review the expense ledger and mark only actual payments.", "expenses"),
    issue("maintenance", "warning", "Maintenance remains unresolved", Number(maintenance?.count || 0), undefined, "Resolve or reschedule open maintenance work.", "maintenance"),
  ].filter((item) => item.count > 0);
  return { expectedRentPaise, billedRentPaise, expectedTenancies: tenancies.length, rentChargeCount: rentCharges.length, readingCount: readings.length, billCount: bills.length, issues, blockingCount: issues.filter((item) => item.severity === "blocking").length };
}

function issue(key: string, severity: "warning" | "blocking", label: string, count: number, amountPaise: number | undefined, explanation: string, actionPage: string) { return { key, severity, label, count, amountPaise, explanation, actionPage }; }

async function setMonthlyClose(db: D1Database, owner: Awaited<ReturnType<typeof requireOwner>>, p: Row) {
  const billingMonth = month(p.billingMonth); const propertyId = str(p.propertyId, "Property"); if (propertyId) await owned(db, "properties", propertyId, owner.key);
  const status = enumValue(p.status, "Closing status", ["draft", "reviewed", "closed"]);
  const existing = await one<Row>(db.prepare("SELECT * FROM monthly_closings WHERE owner_key=? AND billing_month=? AND ((property_id IS NULL AND ?='') OR property_id=?)").bind(owner.key, billingMonth, propertyId, propertyId));
  const checklist = await monthlyChecklist(db, owner.key, billingMonth, propertyId);
  const reason = str(p.reason, "Exception or reopening reason");
  if (existing?.status === "closed" && status !== "closed") { requirePermission(owner, "period.reopen"); if (!reason) throw new ApiError(400, "A reason is required to reopen a closed period."); }
  if (status === "closed" && checklist.blockingCount > 0 && !reason) throw new ApiError(400, "Resolve blocking issues or record an authorized exception reason.");
  const entityId = existing?.id || id("close"); const at = now(); const snapshot = JSON.stringify({ billingMonth, propertyId: propertyId || null, checklist, capturedAt: at });
  if (existing) await db.prepare("UPDATE monthly_closings SET status=?,exception_reason=?,snapshot_json=?,reviewed_at=CASE WHEN ?='reviewed' THEN ? ELSE reviewed_at END,closed_at=CASE WHEN ?='closed' THEN ? ELSE closed_at END,reopened_at=CASE WHEN status='closed' AND ?!='closed' THEN ? ELSE reopened_at END,reopened_reason=CASE WHEN status='closed' AND ?!='closed' THEN ? ELSE reopened_reason END,updated_at=? WHERE id=? AND owner_key=?").bind(status, reason, snapshot, status, at, status, at, status, at, status, reason, at, entityId, owner.key).run();
  else await db.prepare("INSERT INTO monthly_closings (id,owner_key,property_id,billing_month,status,exception_reason,snapshot_json,reviewed_at,closed_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(entityId, owner.key, propertyId || null, billingMonth, status, reason, snapshot, status === "reviewed" ? at : null, status === "closed" ? at : null, at, at).run();
  await audit(db, owner, existing?.status === "closed" && status !== "closed" ? "period.reopened" : `period.${status}`, "monthly_closing", entityId, `${billingMonth} set to ${status}${reason ? `: ${reason}` : ""}`).run();
  return { id: entityId, status, checklist };
}

async function bulkGenerateRent(db: D1Database, owner: Awaited<ReturnType<typeof requireOwner>>, p: Row) {
  const billingMonth = month(p.billingMonth); const ids = stringArray(p.tenancyIds, "tenancy IDs"); const preview = Boolean(p.preview); const out: BulkRowResult[] = [];
  const rates = await rows<Row>(db.prepare("SELECT * FROM rent_rate_history WHERE owner_key=? ORDER BY effective_from").bind(owner.key));
  for (const tenancyId of ids) { try { const tenancy = await owned(db, "tenancies", tenancyId, owner.key); await assertPeriodOpen(db, owner.key, billingMonth, String(tenancy.property_id)); const calc = calculateMonthlyRent(tenancy as any, rates as any, billingMonth); if (!calc) throw new ApiError(400, "No contractual rent applies in this month."); const exists = await one(db.prepare("SELECT id FROM rent_charges WHERE owner_key=? AND tenancy_id=? AND billing_month=? AND source='generated'").bind(owner.key, tenancyId, billingMonth)); if (exists) { out.push({ id: tenancyId, status: "skipped", message: "Rent charge already exists." }); continue; } if (!preview) { const chargeId = id("rent"); const dueDate = `${billingMonth}-${String(Math.min(Number(tenancy.rent_due_day), Number(monthEnd(billingMonth).slice(-2)))).padStart(2, "0")}`; await db.batch([db.prepare("INSERT INTO rent_charges (id,owner_key,tenancy_id,billing_month,period_start,period_end,amount_paise,due_date,source,note,reversed,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, 'generated',?,0,?,?)").bind(chargeId, owner.key, tenancyId, billingMonth, calc.periodStart, calc.periodEnd, calc.amountPaise, dueDate, calc.note, now(), now()), audit(db, owner, "rent.generated", "rent_charge", chargeId, `Generated ${billingMonth} rent in bulk`)]); } out.push({ id: tenancyId, status: "successful", message: preview ? `Will generate ${calc.amountPaise} paise.` : `Generated ${calc.amountPaise} paise.` }); } catch (error) { out.push({ id: tenancyId, status: "failed", message: error instanceof Error ? error.message : "Could not generate rent." }); } }
  return bulkResult(out, preview ? "preview" : "partial");
}

async function bulkFinalizeElectricity(db: D1Database, owner: Awaited<ReturnType<typeof requireOwner>>, p: Row) {
  const ids = stringArray(p.readingIds, "reading IDs"); const preview = Boolean(p.preview); const out: BulkRowResult[] = [];
  for (const readingId of ids) { try { const reading = await owned(db, "electricity_readings", readingId, owner.key); if (reading.status === "finalized") { out.push({ id: readingId, status: "skipped", message: "Already finalized." }); continue; } const tenancy = await owned(db, "tenancies", String(reading.tenancy_id), owner.key); await assertPeriodOpen(db, owner.key, String(reading.billing_month), String(tenancy.property_id)); const rate = await one<Row>(db.prepare("SELECT * FROM electricity_rate_history WHERE owner_key=? AND tenancy_id=? AND effective_from<=? ORDER BY effective_from DESC LIMIT 1").bind(owner.key, reading.tenancy_id, monthEnd(String(reading.billing_month)))); if (!rate) throw new ApiError(400, "No electricity rate applies."); const energy = Math.round(Number(reading.units) * Number(rate.rate_paise_per_unit)); const total = energy + Number(rate.fixed_charge_paise); if (!preview) { const billId = id("ebill"); const at = now(); await db.batch([db.prepare("INSERT INTO electricity_bills (id,owner_key,tenancy_id,reading_id,billing_month,units,rate_paise_per_unit,energy_charge_paise,fixed_charge_paise,adjustment_paise,total_paise,reversed,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,0,?,0,?,?)").bind(billId, owner.key, reading.tenancy_id, readingId, reading.billing_month, reading.units, rate.rate_paise_per_unit, energy, rate.fixed_charge_paise, total, at, at), db.prepare("UPDATE electricity_readings SET status='finalized',updated_at=? WHERE id=? AND owner_key=?").bind(at, readingId, owner.key), audit(db, owner, "electricity.bill_finalized", "electricity_bill", billId, `Bulk finalized ${String(reading.billing_month)} bill`)]); } out.push({ id: readingId, status: "successful", message: preview ? `Will finalize ${total} paise.` : `Finalized ${total} paise.` }); } catch (error) { out.push({ id: readingId, status: "failed", message: error instanceof Error ? error.message : "Could not finalize bill." }); } }
  return bulkResult(out, preview ? "preview" : "partial");
}

async function saveTemplate(db: D1Database, owner: Awaited<ReturnType<typeof requireOwner>>, p: Row) { const kind = enumValue(p.kind, "Template kind", ["rent_due","overdue","payment_acknowledgement","renewal","maintenance"]); const entityId = id("tmpl"); const at = now(); await db.prepare("INSERT INTO communication_templates (id,owner_key,kind,name,body,active,created_at,updated_at) VALUES (?,?,?,?,?,1,?,?) ON CONFLICT(owner_key,kind) DO UPDATE SET name=excluded.name,body=excluded.body,active=1,updated_at=excluded.updated_at").bind(entityId, owner.key, kind, str(p.name, "Template name", true), str(p.body, "Template body", true), at, at).run(); await audit(db, owner, "communication.template_saved", "communication_template", kind, `Saved ${kind} template`).run(); return { kind }; }

async function prepareCommunication(db: D1Database, owner: Awaited<ReturnType<typeof requireOwner>>, p: Row) { const tenantId = str(p.tenantId, "Tenant", true); const tenant = await owned(db, "tenants", tenantId, owner.key); const tenancyId = str(p.tenancyId, "Tenancy"); if (tenancyId) { const tenancy = await owned(db, "tenancies", tenancyId, owner.key); if (String(tenancy.tenant_id) !== tenantId) throw new ApiError(400, "Tenancy does not belong to this tenant."); } const channel = enumValue(p.channel, "Channel", ["whatsapp","clipboard","email"]); if (channel === "email") throw new ApiError(409, "Automatic email is disabled until a provider is configured and authorized."); const preference = await one<Row>(db.prepare("SELECT opted_out FROM communication_preferences WHERE owner_key=? AND tenant_id=? AND channel=?").bind(owner.key, tenantId, channel)); if (preference?.opted_out) throw new ApiError(409, "This tenant has opted out of this communication channel."); const entityId = id("comm"); const at = now(); const status = enumValue(p.status, "Communication status", ["prepared","opened","copied"], "prepared"); await db.batch([db.prepare("INSERT INTO communication_events (id,owner_key,tenant_id,tenancy_id,template_kind,channel,recipient,message_snapshot,status,next_follow_up_date,promised_payment_date,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(entityId, owner.key, tenantId, tenancyId || null, str(p.templateKind, "Template kind", true), channel, str(p.recipient, "Recipient", true), str(p.message, "Message", true), status, optionalDate(p.nextFollowUpDate, "Next follow-up"), optionalDate(p.promisedPaymentDate, "Promised payment"), owner.userKey, at, at), audit(db, owner, "communication.prepared", "communication_event", entityId, `${channel} message prepared for ${String(tenant.full_name)}; delivery not confirmed`)]); return { id: entityId, status, deliveryConfirmed: false }; }

async function setCommunicationPreference(db: D1Database, owner: Awaited<ReturnType<typeof requireOwner>>, p: Row) { const tenantId = str(p.tenantId, "Tenant", true); await owned(db, "tenants", tenantId, owner.key); const channel = enumValue(p.channel, "Channel", ["whatsapp","email"]); const optedOut = p.optedOut ? 1 : 0; const at = now(); await db.prepare("INSERT INTO communication_preferences (id,owner_key,tenant_id,channel,opted_out,reason,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(owner_key,tenant_id,channel) DO UPDATE SET opted_out=excluded.opted_out,reason=excluded.reason,updated_at=excluded.updated_at").bind(id("pref"), owner.key, tenantId, channel, optedOut, str(p.reason, "Reason"), at, at).run(); return { tenantId, channel, optedOut: Boolean(optedOut) }; }

async function importBankTransactions(db: D1Database, owner: Awaited<ReturnType<typeof requireOwner>>, p: Row) { const source = Array.isArray(p.rows) ? p.rows : []; if (!source.length) throw new ApiError(400, "Add at least one bank transaction row."); if (source.length > 1000) throw new ApiError(400, "Import at most 1,000 rows at a time."); const preview = !p.commit; const seen = new Set<string>(); const valid: Row[] = []; const results: BulkRowResult[] = []; for (let i=0;i<source.length;i++) { try { const raw=safeJson(source[i]); const transactionDate=isoDate(raw.transactionDate, "Transaction date"); const amountPaise=int(raw.amountPaise,"Amount",1); const direction=enumValue(raw.direction,"Direction",["credit","debit"]); const description=str(raw.description,"Description",true); const reference=str(raw.reference,"Reference"); const fingerprint=await digest(`${transactionDate}|${amountPaise}|${direction}|${reference.toLowerCase()}|${description.toLowerCase()}`); if(seen.has(fingerprint)) { results.push({id:String(i+1),status:"skipped",message:"Duplicate row inside this file."}); continue; } seen.add(fingerprint); const exists=await one(db.prepare("SELECT id FROM bank_transactions WHERE owner_key=? AND fingerprint=?").bind(owner.key,fingerprint)); if(exists){results.push({id:String(i+1),status:"skipped",message:"Already imported previously."});continue;} valid.push({transactionDate,amountPaise,direction,description,reference,fingerprint}); results.push({id:String(i+1),status:"successful",message:preview?"Valid and ready.":"Imported."}); } catch(error){results.push({id:String(i+1),status:"failed",message:error instanceof Error?error.message:"Invalid row."});} }
  if (!preview && valid.length) { const importId=id("bankimp"); const at=now(); const fileHash=await digest(JSON.stringify(valid)); const stmts:D1PreparedStatement[]=[db.prepare("INSERT INTO bank_imports (id,owner_key,filename,file_hash,mapping_json,row_count,imported_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(importId,owner.key,str(p.filename,"Filename")||"bank-statement.csv",fileHash,JSON.stringify(safeJson(p.mapping)),valid.length,at,at,at)]; valid.forEach(row=>stmts.push(db.prepare("INSERT INTO bank_transactions (id,owner_key,import_id,transaction_date,amount_paise,direction,description,reference,fingerprint,status,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,'unmatched',1,?,?)").bind(id("banktx"),owner.key,importId,row.transactionDate,row.amountPaise,row.direction,row.description,row.reference,row.fingerprint,at,at))); stmts.push(audit(db,owner,"bank.imported","bank_import",importId,`Imported ${valid.length} bank transactions`)); await db.batch(stmts); }
  return { ...bulkResult(results, preview?"preview":"partial"), validRows: valid.length };
}

async function reconcileBankTransaction(db: D1Database, owner: Awaited<ReturnType<typeof requireOwner>>, p: Row) { const transactionId=str(p.transactionId,"Bank transaction",true); const transaction=await one<Row>(db.prepare("SELECT * FROM bank_transactions WHERE id=? AND owner_key=?").bind(transactionId,owner.key)); if(!transaction)throw new ApiError(404,"Bank transaction not found."); if(transaction.status!=="unmatched")throw new ApiError(409,"This transaction is already reconciled."); const expectedVersion=int(p.version??transaction.version,"Version",1); if(Number(transaction.version)!==expectedVersion)throw new ApiError(409,"This transaction changed. Refresh before confirming."); const matchType=enumValue(p.matchType,"Match type",["existing_payment","new_payment","deposit","expense","non_rental"]); let paymentId:string|null=null; let createdPayment=0; const at=now(); const stmts:D1PreparedStatement[]=[]; if(matchType==="existing_payment"){paymentId=str(p.paymentId,"Payment",true); const payment=await owned(db,"payments",paymentId,owner.key); if(payment.status!=="recorded"||Number(payment.amount_paise)!==Number(transaction.amount_paise))throw new ApiError(400,"Existing payment must be recorded and match the bank amount exactly.");} if(matchType==="new_payment"){if(transaction.direction!=="credit")throw new ApiError(400,"Only a bank credit can create a rent payment."); const tenancyId=str(p.tenancyId,"Tenancy",true); const tenancy=await owned(db,"tenancies",tenancyId,owner.key); paymentId=id("pay"); createdPayment=1; stmts.push(db.prepare("INSERT INTO payments (id,owner_key,tenancy_id,tenant_id,amount_paise,payment_date,mode,reference,notes,request_key,status,created_at,updated_at) VALUES (?,?,?,?,?,?,'bank_transfer',?,'Created from reviewed bank reconciliation',?,'recorded',?,?)").bind(paymentId,owner.key,tenancyId,tenancy.tenant_id,transaction.amount_paise,transaction.transaction_date,transaction.reference||transaction.description,`bank:${transactionId}`,at,at));}
  const matchId=id("match"); stmts.push(db.prepare("INSERT INTO reconciliation_matches (id,owner_key,bank_transaction_id,payment_id,match_type,evidence_json,created_payment,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(matchId,owner.key,transactionId,paymentId,matchType,JSON.stringify(safeJson(p.evidence)),createdPayment,at,at),db.prepare("UPDATE bank_transactions SET status='matched',version=version+1,updated_at=? WHERE id=? AND owner_key=? AND version=?").bind(at,transactionId,owner.key,expectedVersion),audit(db,owner,"bank.matched","bank_transaction",transactionId,`Confirmed ${matchType} reconciliation`)); await db.batch(stmts); return{id:matchId,paymentId,createdPayment:Boolean(createdPayment)}; }

async function undoBankReconciliation(db: D1Database, owner: Awaited<ReturnType<typeof requireOwner>>, p: Row) { const transactionId=str(p.transactionId,"Bank transaction",true); const reason=str(p.reason,"Undo reason",true); const match=await one<Row>(db.prepare("SELECT * FROM reconciliation_matches WHERE owner_key=? AND bank_transaction_id=? AND reversed_at IS NULL ORDER BY created_at DESC LIMIT 1").bind(owner.key,transactionId)); if(!match)throw new ApiError(404,"Active reconciliation not found."); const at=now(); const stmts=[db.prepare("UPDATE reconciliation_matches SET reversed_at=?,reversal_reason=?,updated_at=? WHERE id=? AND owner_key=?").bind(at,reason,at,match.id,owner.key),db.prepare("UPDATE bank_transactions SET status='unmatched',version=version+1,updated_at=? WHERE id=? AND owner_key=?").bind(at,transactionId,owner.key),audit(db,owner,"bank.match_undone","bank_transaction",transactionId,`Reconciliation undone: ${reason}`)]; if(match.created_payment&&match.payment_id)stmts.push(db.prepare("UPDATE payments SET status='reversed',reversed_at=?,reversal_reason=?,updated_at=? WHERE id=? AND owner_key=?").bind(at,`Bank match undone: ${reason}`,at,match.payment_id,owner.key)); await db.batch(stmts); return{id:transactionId}; }

async function createPaymentRequest(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row,requestKey:string){const tenancyId=str(p.tenancyId,"Tenancy",true);const tenancy=await owned(db,"tenancies",tenancyId,owner.key);const amountPaise=int(p.amountPaise,"Amount",1);const reference=str(p.reference,"Reference",true);const expiresAt=str(p.expiresAt,"Expiry",true);if(Number.isNaN(Date.parse(expiresAt)))throw new ApiError(400,"Expiry is invalid.");const settings=await one<Row>(db.prepare("SELECT upi_id,landlord_name FROM settings WHERE owner_key=?").bind(owner.key));const upiId=String(settings?.upi_id||"");if(!upiId)throw new ApiError(409,"Add a UPI ID in Settings before creating a payment request.");const upiUri=`upi://pay?pa=${encodeURIComponent(upiId)}&pn=${encodeURIComponent(String(settings?.landlord_name||"Landlord"))}&am=${(amountPaise/100).toFixed(2)}&cu=INR&tn=${encodeURIComponent(reference)}`;const entityId=id("payreq");const at=now();await db.batch([db.prepare("INSERT INTO payment_requests (id,owner_key,tenancy_id,tenant_id,amount_paise,reference,expires_at,status,upi_uri,provider,request_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'pending',?,'manual_upi',?,?,?)").bind(entityId,owner.key,tenancyId,tenancy.tenant_id,amountPaise,reference,expiresAt,upiUri,requestKey,at,at),audit(db,owner,"payment_request.created","payment_request",entityId,"Created UPI payment instructions; payment remains unverified")]);return{id:entityId,status:"pending",upiUri,verified:false};}

async function confirmPaymentRequest(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){const entityId=str(p.id,"Payment request",true);const paymentId=str(p.paymentId,"Payment",true);const request=await one<Row>(db.prepare("SELECT * FROM payment_requests WHERE id=? AND owner_key=?").bind(entityId,owner.key));if(!request)throw new ApiError(404,"Payment request not found.");const payment=await owned(db,"payments",paymentId,owner.key);if(String(payment.tenancy_id)!==String(request.tenancy_id)||payment.status!=="recorded")throw new ApiError(400,"Confirmed payment must be a recorded payment for the same tenancy.");await db.batch([db.prepare("UPDATE payment_requests SET status='successful',confirmed_payment_id=?,updated_at=? WHERE id=? AND owner_key=?").bind(paymentId,now(),entityId,owner.key),audit(db,owner,"payment_request.confirmed","payment_request",entityId,`Linked verified payment ${paymentId}`)]);return{id:entityId,status:"successful"};}

async function createInspection(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){const propertyId=str(p.propertyId,"Property",true);const roomId=str(p.roomId,"Room",true);const property=await owned(db,"properties",propertyId,owner.key);const room=await owned(db,"rooms",roomId,owner.key);if(String(room.property_id)!==propertyId)throw new ApiError(400,"Room does not belong to this property.");const tenancyId=str(p.tenancyId,"Tenancy");let tenantId:string|null=null;if(tenancyId){const tenancy=await owned(db,"tenancies",tenancyId,owner.key);if(String(tenancy.room_id)!==roomId)throw new ApiError(400,"Tenancy does not belong to this room.");tenantId=String(tenancy.tenant_id);}const type=enumValue(p.inspectionType,"Inspection type",["move_in","move_out"]);const items=Array.isArray(p.items)?p.items:[];const entityId=id("inspect");const at=now();const stmts:D1PreparedStatement[]=[db.prepare("INSERT INTO inspections (id,owner_key,property_id,room_id,tenant_id,tenancy_id,inspection_type,inspection_date,status,meter_number,meter_reading,keys_json,notes,acknowledgement_status,snapshot_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,'draft',?,?,?,?,?,'pending','{}',?,?)").bind(entityId,owner.key,propertyId,roomId,tenantId,tenancyId||null,type,isoDate(p.inspectionDate,"Inspection date"),str(p.meterNumber,"Meter number"),p.meterReading==null?null:Number(p.meterReading),JSON.stringify(Array.isArray(p.keys)?p.keys:[]),str(p.notes,"Notes"),at,at)];for(const raw of items){const item=safeJson(raw);stmts.push(db.prepare("INSERT INTO inspection_items (id,owner_key,inspection_id,area,item_name,condition,existing_damage,description,photo_document_id,proposed_deduction_paise,deduction_status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?, 'proposed',?)").bind(id("item"),owner.key,entityId,str(item.area,"Area",true),str(item.itemName,"Item",true),enumValue(item.condition,"Condition",["good","fair","damaged","missing"]),item.existingDamage?1:0,str(item.description,"Description"),str(item.photoDocumentId,"Photo")||null,int(item.proposedDeductionPaise??0,"Proposed deduction",0),at));}stmts.push(audit(db,owner,"inspection.created","inspection",entityId,`Created ${type} inspection for ${String(property.name)} room ${String(room.room_number)}`));await db.batch(stmts);return{id:entityId};}

async function finalizeInspection(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){const entityId=str(p.id,"Inspection",true);const inspection=await one<Row>(db.prepare("SELECT * FROM inspections WHERE id=? AND owner_key=?").bind(entityId,owner.key));if(!inspection)throw new ApiError(404,"Inspection not found.");const items=await rows<Row>(db.prepare("SELECT * FROM inspection_items WHERE inspection_id=? AND owner_key=?").bind(entityId,owner.key));const at=now();const snapshot=JSON.stringify({inspection,items,finalizedAt:at});await db.batch([db.prepare("UPDATE inspections SET status='finalized',acknowledgement_status=?,snapshot_json=?,updated_at=? WHERE id=? AND owner_key=?").bind(enumValue(p.acknowledgementStatus,"Acknowledgement",["pending","acknowledged","declined"]),snapshot,at,entityId,owner.key),audit(db,owner,"inspection.finalized","inspection",entityId,"Finalized inspection evidence; deductions remain proposed")]);return{id:entityId,status:"finalized"};}

async function createRenewal(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){const tenancyId=str(p.tenancyId,"Tenancy",true);await owned(db,"tenancies",tenancyId,owner.key);const entityId=id("renew");const at=now();await db.batch([db.prepare("INSERT INTO lease_renewals (id,owner_key,tenancy_id,proposed_rent_paise,proposed_deposit_paise,proposed_start_date,proposed_end_date,notice_terms,status,tenant_response,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, 'draft','',?,?)").bind(entityId,owner.key,tenancyId,int(p.proposedRentPaise,"Proposed rent",1),int(p.proposedDepositPaise??0,"Proposed deposit",0),isoDate(p.proposedStartDate,"Start date"),optionalDate(p.proposedEndDate,"End date"),str(p.noticeTerms,"Notice terms"),at,at),audit(db,owner,"renewal.created","lease_renewal",entityId,"Created draft renewal; billing unchanged")]);return{id:entityId,status:"draft"};}

async function setRenewalStatus(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){const entityId=str(p.id,"Renewal",true);const renewal=await one<Row>(db.prepare("SELECT * FROM lease_renewals WHERE id=? AND owner_key=?").bind(entityId,owner.key));if(!renewal)throw new ApiError(404,"Renewal not found.");const status=enumValue(p.status,"Renewal status",["draft","sent","accepted","declined","expired"]);const applyRate=Boolean(p.applyRate);if(applyRate&&status!=="accepted")throw new ApiError(400,"A rent change can be approved only after acceptance.");if(applyRate){const tenancy=await owned(db,"tenancies",String(renewal.tenancy_id),owner.key);await assertPeriodOpen(db,owner.key,String(renewal.proposed_start_date).slice(0,7),String(tenancy.property_id));}const at=now();const stmts:D1PreparedStatement[]=[db.prepare("UPDATE lease_renewals SET status=?,tenant_response=?,accepted_at=CASE WHEN ?='accepted' THEN ? ELSE accepted_at END,approved_at=CASE WHEN ?=1 THEN ? ELSE approved_at END,updated_at=? WHERE id=? AND owner_key=?").bind(status,str(p.tenantResponse,"Tenant response"),status,at,applyRate?1:0,at,at,entityId,owner.key)];if(applyRate){stmts.push(db.prepare("INSERT INTO rent_rate_history (id,owner_key,tenancy_id,amount_paise,effective_from,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").bind(id("rr"),owner.key,renewal.tenancy_id,renewal.proposed_rent_paise,renewal.proposed_start_date,at,at));}stmts.push(audit(db,owner,applyRate?"renewal.approved":"renewal.status_changed","lease_renewal",entityId,applyRate?"Accepted renewal approved and effective-dated rate created":`Renewal set to ${status}; billing unchanged`));await db.batch(stmts);return{id:entityId,status,rateApplied:applyRate};}

async function updateOnboarding(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){if(!Array.isArray(p.completedSteps))throw new ApiError(400,"Completed steps must be a list.");const completed=p.completedSteps.map((value)=>int(value,"Completed step",1,7));const current=int(p.currentStep??1,"Current step",1,7);const at=now();await db.prepare("INSERT INTO onboarding_progress (owner_key,current_step,completed_steps_json,dismissed_at,created_at,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(owner_key) DO UPDATE SET current_step=excluded.current_step,completed_steps_json=excluded.completed_steps_json,dismissed_at=excluded.dismissed_at,updated_at=excluded.updated_at").bind(owner.key,current,JSON.stringify([...new Set(completed)]),p.dismissed?at:null,at,at).run();return{currentStep:current,completedSteps:completed};}

async function createInvitation(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){const email=str(p.email,"Email",true).toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))throw new ApiError(400,"Email is invalid.");const role=enumValue(p.role,"Role",["manager","accountant","read_only"]);const expiresAt=str(p.expiresAt,"Expiry",true);if(Date.parse(expiresAt)<=Date.now())throw new ApiError(400,"Invitation expiry must be in the future.");const token=crypto.randomUUID()+crypto.randomUUID();const tokenHash=await digest(token);const entityId=id("invite");const at=now();await db.batch([db.prepare("INSERT INTO workspace_invitations (id,owner_key,email,role,token_hash,status,expires_at,invited_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,'pending',?,?,?,?)").bind(entityId,owner.key,email,role,tokenHash,expiresAt,owner.userKey,at,at),audit(db,owner,"member.invited","workspace_invitation",entityId,`Prepared ${role} invitation for ${email}`)]);return{id:entityId,token,acceptPath:`/?invite=${encodeURIComponent(token)}`,deliverySent:false};}

async function revokeInvitation(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){const entityId=str(p.id,"Invitation",true);const result=await db.prepare("UPDATE workspace_invitations SET status='revoked',updated_at=? WHERE id=? AND owner_key=? AND status='pending'").bind(now(),entityId,owner.key).run();if(!result.meta.changes)throw new ApiError(404,"Pending invitation not found.");await audit(db,owner,"member.invitation_revoked","workspace_invitation",entityId,"Revoked workspace invitation").run();return{id:entityId};}

async function acceptInvitation(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){const token=str(p.token,"Invitation token",true);const hash=await digest(token);const invitation=await one<Row>(db.prepare("SELECT * FROM workspace_invitations WHERE token_hash=? AND status='pending'").bind(hash));if(!invitation||Date.parse(invitation.expires_at)<=Date.now())throw new ApiError(404,"Invitation is invalid or expired.");if(String(invitation.email).toLowerCase()!==owner.email.toLowerCase())throw new ApiError(403,"Sign in with the email address that was invited.");const at=now();await db.batch([db.prepare("INSERT INTO workspace_memberships (id,workspace_id,user_id,role,status,created_at,updated_at) VALUES (?,?,?,?, 'active',?,?) ON CONFLICT(workspace_id,user_id) DO UPDATE SET role=excluded.role,status='active',updated_at=excluded.updated_at").bind(id("membership"),invitation.owner_key,owner.userKey,invitation.role,at,at),db.prepare("UPDATE workspace_invitations SET status='accepted',accepted_by_user_id=?,accepted_at=?,updated_at=? WHERE id=?").bind(owner.userKey,at,at,invitation.id),db.prepare("INSERT INTO audit_log (id,owner_key,action,entity_type,entity_id,summary,actor_context,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(id("aud"),invitation.owner_key,"member.joined","workspace_membership",owner.userKey,`${owner.email} accepted a ${invitation.role} invitation`,owner.email,at)]);return{workspaceId:invitation.owner_key,role:invitation.role};}

async function setMemberRole(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){const membershipId=str(p.id,"Membership",true);const role=enumValue(p.role,"Role",["manager","accountant","read_only"]);const membership=await one<Row>(db.prepare("SELECT * FROM workspace_memberships WHERE id=? AND workspace_id=?").bind(membershipId,owner.key));if(!membership)throw new ApiError(404,"Membership not found.");if(membership.user_id===owner.userKey||membership.role==="owner")throw new ApiError(400,"The workspace owner role cannot be changed here.");await db.batch([db.prepare("UPDATE workspace_memberships SET role=?,updated_at=? WHERE id=? AND workspace_id=?").bind(role,now(),membershipId,owner.key),audit(db,owner,"member.role_changed","workspace_membership",membershipId,`Changed member role to ${role}`)]);return{id:membershipId,role};}

async function revokeMember(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){const membershipId=str(p.id,"Membership",true);const membership=await one<Row>(db.prepare("SELECT * FROM workspace_memberships WHERE id=? AND workspace_id=?").bind(membershipId,owner.key));if(!membership)throw new ApiError(404,"Membership not found.");if(membership.user_id===owner.userKey||membership.role==="owner")throw new ApiError(400,"The workspace owner cannot be revoked.");await db.batch([db.prepare("UPDATE workspace_memberships SET status='revoked',updated_at=? WHERE id=? AND workspace_id=?").bind(now(),membershipId,owner.key),audit(db,owner,"member.revoked","workspace_membership",membershipId,"Revoked member access immediately")]);return{id:membershipId};}

async function configureTestPlan(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){const planName=str(p.name,"Plan name",true);const roomLimit=int(p.roomLimit,"Room limit",1,100000);const existing=await one<Row>(db.prepare("SELECT * FROM workspace_subscriptions WHERE owner_key=?").bind(owner.key));const planId=String(existing?.plan_id||id("plan"));const at=now();await db.batch([db.prepare("INSERT INTO subscription_plans (id,name,room_limit,features_json,price_paise,active,created_at,updated_at) VALUES (?,?,?,?,NULL,1,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,room_limit=excluded.room_limit,features_json=excluded.features_json,updated_at=excluded.updated_at").bind(planId,planName,roomLimit,JSON.stringify(Array.isArray(p.features)?p.features:[]),at,at),db.prepare("INSERT INTO workspace_subscriptions (id,owner_key,plan_id,status,provider,created_at,updated_at) VALUES (?,?,?,'test','test',?,?) ON CONFLICT(owner_key) DO UPDATE SET plan_id=excluded.plan_id,status='test',provider='test',updated_at=excluded.updated_at").bind(id("sub"),owner.key,planId,at,at),audit(db,owner,"subscription.test_configured","workspace_subscription",owner.key,`Configured test plan ${planName}; no charge created`)]);return{planId,status:"test",charged:false};}

async function createBackup(db:D1Database,owner:Awaited<ReturnType<typeof requireOwner>>,p:Row){const backupType=enumValue(p.backupType,"Backup type",["structured"]);const tableNames=["properties","rooms","tenants","tenancies","rent_rate_history","electricity_rate_history","rent_charges","electricity_readings","electricity_bills","other_charges","payments","payment_allocations","deposit_ledger","receipts","documents","follow_ups","expenses","maintenance_issues","monthly_closings","communication_events","bank_transactions","reconciliation_matches","payment_requests","inspections","inspection_items","lease_renewals"] as const;const records:Row={};let recordCount=0;for(const table of tableNames){records[table]=await rows(db.prepare(`SELECT * FROM ${table} WHERE owner_key=?`).bind(owner.key));recordCount+=records[table].length;}const tenancyIds=new Set(records.tenancies.map((row:Row)=>row.id));const tenantIds=new Set(records.tenants.map((row:Row)=>row.id));const roomIds=new Set(records.rooms.map((row:Row)=>row.id));const propertyIds=new Set(records.properties.map((row:Row)=>row.id));const paymentIds=new Set(records.payments.map((row:Row)=>row.id));const orphanCount=records.tenancies.filter((row:Row)=>!tenantIds.has(row.tenant_id)||!roomIds.has(row.room_id)||!propertyIds.has(row.property_id)).length+records.payment_allocations.filter((row:Row)=>!paymentIds.has(row.payment_id)).length;if(orphanCount)throw new ApiError(409,`Backup verification found ${orphanCount} broken relationship(s). Repair them before creating a verified snapshot.`);const payload={schemaVersion:5,workspace:{id:owner.key,name:owner.workspaceName},createdAt:now(),backupType,records};const json=JSON.stringify(payload);const checksum=await digest(json);const entityId=id("backup");const objectKey=`${owner.key}/backups/${entityId}.json`;await bucket().put(objectKey,json,{httpMetadata:{contentType:"application/json"}});const documentCount=records.documents.length;const verification=JSON.stringify({workspaceValid:true,relationshipsChecked:true,orphanCount,integrityTotals:{payments:records.payments.reduce((s:number,r:Row)=>s+Number(r.amount_paise),0),allocations:records.payment_allocations.filter((r:Row)=>!r.reversed).reduce((s:number,r:Row)=>s+Number(r.amount_paise),0)},documentsIncluded:false});const at=now();await db.batch([db.prepare("INSERT INTO backup_snapshots (id,owner_key,backup_type,status,schema_version,record_count,document_count,checksum,object_key,verification_json,created_by_user_id,verified_at,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(entityId,owner.key,backupType,"verified",5,recordCount,documentCount,checksum,objectKey,verification,owner.userKey,at,at),audit(db,owner,"backup.created","backup_snapshot",entityId,`Created and verified ${backupType} backup with ${recordCount} records`)]);return{id:entityId,recordCount,documentCount,checksum,status:"verified",documentsIncluded:false};}

async function bankInbox(db:D1Database,ownerKey:string,limit:number,offset:number){const list=await rows<Row>(db.prepare("SELECT * FROM bank_transactions WHERE owner_key=? ORDER BY CASE status WHEN 'unmatched' THEN 0 ELSE 1 END,transaction_date DESC LIMIT ? OFFSET ?").bind(ownerKey,limit,offset));for(const transaction of list){if(transaction.status!=="unmatched"||transaction.direction!=="credit")continue;const candidates=await rows<Row>(db.prepare("SELECT p.id,p.amount_paise,p.payment_date,p.reference,t.full_name FROM payments p JOIN tenants t ON t.id=p.tenant_id WHERE p.owner_key=? AND p.status='recorded' AND p.amount_paise=? AND ABS(julianday(p.payment_date)-julianday(?))<=3 ORDER BY CASE WHEN lower(p.reference)=lower(?) AND ?<>'' THEN 0 ELSE 1 END,p.payment_date LIMIT 3").bind(ownerKey,transaction.amount_paise,transaction.transaction_date,transaction.reference,transaction.reference));transaction.suggestions=candidates.map(candidate=>({paymentId:candidate.id,tenant:candidate.full_name,confidence:candidate.reference&&transaction.reference&&String(candidate.reference).toLowerCase()===String(transaction.reference).toLowerCase()?"high":"medium",explanation:candidate.reference&&transaction.reference&&String(candidate.reference).toLowerCase()===String(transaction.reference).toLowerCase()?"Exact amount and reference; payment date is within three days.":"Exact amount and payment date is within three days; reference differs or is missing."}));}return list;}

async function assertPeriodOpen(db:D1Database,ownerKey:string,billingMonth:string,propertyId:string){const closed=await one(db.prepare("SELECT id FROM monthly_closings WHERE owner_key=? AND billing_month=? AND status='closed' AND (property_id IS NULL OR property_id=?) LIMIT 1").bind(ownerKey,billingMonth,propertyId));if(closed)throw new ApiError(409,"This month is closed. Reopen it with a recorded reason before editing financial records.");}
async function owned(db:D1Database,table:string,entityId:string,ownerKey:string){const allowed=new Set(["properties","rooms","tenants","tenancies","payments","electricity_readings"]);if(!allowed.has(table))throw new ApiError(500,"Invalid record lookup.");const row=await one<Row>(db.prepare(`SELECT * FROM ${table} WHERE id=? AND owner_key=?`).bind(entityId,ownerKey));if(!row)throw new ApiError(404,"Record not found.");return row;}
function enumValue(value:unknown,label:string,allowed:string[],fallback?:string){const candidate=str(value,label)||fallback||"";if(!allowed.includes(candidate))throw new ApiError(400,`${label} is invalid.`);return candidate;}
function optionalDate(value:unknown,label:string){const candidate=str(value,label);return candidate?isoDate(candidate,label):null;}
function stringArray(value:unknown,label:string){if(!Array.isArray(value))throw new ApiError(400,`${label} must be a list.`);return value.map((item)=>str(item,label,true));}
function bulkResult(rows:BulkRowResult[],mode:string){return{mode,atomic:false,rows,successful:rows.filter(row=>row.status==="successful").length,skipped:rows.filter(row=>row.status==="skipped").length,failed:rows.filter(row=>row.status==="failed").length};}
async function digest(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
function monthEnd(value:string){const[y,m]=value.split("-").map(Number);return new Date(Date.UTC(y,m,0)).toISOString().slice(0,10);}
function currentMonth(){return new Date().toISOString().slice(0,7);}
function today(){return new Date().toISOString().slice(0,10);}
