"use client";

import { AlertTriangle, ArrowRight, Banknote, Building2, CalendarClock, CircleDollarSign, Gauge, Home, IndianRupee, Plus, ReceiptText, TrendingUp, WalletCards, Wrench, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { buildDashboardAnalysis } from "./dashboard-analysis";

type Row = Record<string, any>;

export function AdvancedDashboard({ data, month, propertyFilter, open, setPage, runAction }: any) {
  const analysis = buildDashboardAnalysis(data, month, propertyFilter);
  const go = (page: string) => setPage(page);
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-black tracking-tight text-slate-900">Portfolio dashboard</h2><p className="mt-1 text-sm text-slate-500">Reporting basis: saved ledger records · as of {formatDate(new Date().toISOString().slice(0, 10))}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => open("expense")}><Plus /> Expense</Button><Button variant="outline" onClick={() => open("maintenance")}><Wrench /> Maintenance</Button><Button onClick={() => open("payment")}><Plus /> Payment</Button></div></div>
    <Tabs defaultValue="overview" className="dashboard-tabs">
      <TabsList variant="line" className="dashboard-tabs-list w-full justify-start"><TabsTrigger value="overview"><Home /> Overview</TabsTrigger><TabsTrigger value="collections"><IndianRupee /> Collections</TabsTrigger><TabsTrigger value="properties"><Building2 /> Properties</TabsTrigger><TabsTrigger value="electricity"><Zap /> Electricity</TabsTrigger><TabsTrigger value="expenses"><WalletCards /> Expenses</TabsTrigger></TabsList>
      <TabsContent value="overview" className="mt-5 space-y-5">
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-8"><MetricButton label="Expected rent" value={money(analysis.expectedRent)} icon={TrendingUp} onClick={() => go("rent")} /><MetricButton label="Billed rent" value={money(analysis.billedRent)} icon={ReceiptText} onClick={() => go("rent")} /><MetricButton label="Payments received" value={money(analysis.paymentsReceived)} icon={Banknote} positive onClick={() => go("payments")} /><MetricButton label="Applied to bills" value={money(analysis.collectionsAgainstBills)} icon={CircleDollarSign} positive onClick={() => go("payments")} /><MetricButton label="Outstanding" value={money(analysis.outstanding)} icon={AlertTriangle} warning onClick={() => go("rent")} /><MetricButton label="Unapplied credit" value={money(analysis.unappliedCredit)} icon={WalletCards} onClick={() => go("payments")} /><MetricButton label="Deposits held" value={money(analysis.depositsHeld)} icon={Banknote} onClick={() => go("tenants")} /><MetricButton label="Occupancy" value={`${analysis.occupancy.occupied}/${analysis.occupancy.total}`} icon={Home} onClick={() => go("rooms")} /></div>
        <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Panel title="Needs attention" subtitle="Each item opens the records needed to act"><div className="divide-y divide-slate-100">{analysis.attention.length ? analysis.attention.map((item: Row) => <button key={item.type} onClick={() => item.action ? open(item.action) : go(item.page)} className="flex min-h-14 w-full items-center gap-3 px-5 py-3 text-left hover:bg-slate-50"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-orange-50 text-orange-700"><AlertTriangle className="size-4" /></span><span className="min-w-0 flex-1"><b className="block text-sm text-slate-900">{item.label}</b>{item.amount ? <span className="text-xs text-slate-500">{money(item.amount)} requires review</span> : null}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-sm font-bold">{item.count}</span><ArrowRight className="size-4 text-slate-400" /></button>) : <Empty text="Nothing requires immediate action for this view." />}</div></Panel><Panel title="Upcoming 45 days" subtitle="Renewals, rate changes and planned move-outs"><div className="divide-y divide-slate-100">{analysis.upcoming.length ? analysis.upcoming.map((item: Row, index: number) => <div key={`${item.date}-${index}`} className="flex gap-3 px-5 py-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-700"><CalendarClock className="size-4" /></span><div><b className="text-sm text-slate-900">{item.type} · {formatDate(item.date)}</b><p className="mt-0.5 text-xs text-slate-500">{item.tenant} · {item.location}</p></div></div>) : <Empty text="No scheduled events in the next 45 days." />}</div></Panel></div>
        <Panel title="Tenants with outstanding balances" subtitle="Includes active and former tenants"><DataRows columns={["Tenant", "Location", "Oldest due", "Outstanding", "Status"]} rows={analysis.tenantDues.slice(0, 10).map((row: Row) => [row.tenant, `${row.property} · Room ${row.room}`, formatDate(row.oldestDue), money(row.amount), label(row.status)])} empty="No tenant balances are outstanding." /></Panel>
      </TabsContent>
      <TabsContent value="collections" className="mt-5 space-y-5">
        <div className="grid gap-4 lg:grid-cols-2"><Panel title="12-month collection trend" subtitle="Money received is separate from money applied to bills"><TrendChart rows={analysis.trends} series={[{ key: "received", label: "Received", color: "bg-emerald-500" }, { key: "collected", label: "Applied", color: "bg-violet-500" }]} /></Panel><Panel title="Dues ageing" subtitle="Current unpaid charge balances by due date"><div className="space-y-4 p-5">{analysis.ageing.map((bucket: Row) => <Bar key={bucket.label} label={bucket.label} value={bucket.value} max={Math.max(...analysis.ageing.map((item: Row) => item.value), 1)} moneyValue />)}</div></Panel></div>
        <Panel title="Expected, billed and received" subtitle="Contractual rent can be expected before generation"><TrendChart rows={analysis.trends.slice(-6)} series={[{ key: "expected", label: "Expected rent", color: "bg-slate-300" }, { key: "billed", label: "All billed", color: "bg-blue-500" }, { key: "received", label: "Cash received", color: "bg-emerald-500" }]} /></Panel>
      </TabsContent>
      <TabsContent value="properties" className="mt-5"><Panel title="Property comparison" subtitle="Historical room-day fields show unavailable until explicit availability history exists"><DataRows columns={["Property", "Expected", "Billed", "Received", "Outstanding", "Expenses", "Occupancy", "Room days", "Turnover", "Avg stay", "Vacancy estimate"]} rows={analysis.properties.map((row: Row) => [row.name, money(row.expected), money(row.billed), money(row.received), money(row.outstanding), money(row.expenses), row.occupancy, row.availabilityKnown ? `${row.occupiedDays} occupied · ${row.vacantDays} vacant` : "Unavailable", row.turnover, row.averageStayDays ? `${row.averageStayDays} days` : "Unavailable", row.availabilityKnown && row.vacancyLossEstimate > 0 ? `${money(row.vacancyLossEstimate)} estimated` : row.availabilityKnown ? "₹0" : "Unavailable"])} empty="Add an active property to compare performance." /></Panel></TabsContent>
      <TabsContent value="electricity" className="mt-5 space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Summary label="Billed this month" value={money(analysis.electricityBilled)} /><Summary label="Missing readings" value={String(analysis.attention.find((item: Row) => item.type === "reading")?.count || 0)} /><Summary label="Draft bills" value={String(analysis.attention.find((item: Row) => item.type === "draft")?.count || 0)} /></div>{analysis.electricityWarnings.length > 0 && <Panel title="Unusual consumption" subtitle="Warnings compare normalized daily usage with recent saved intervals"><div className="divide-y divide-slate-100">{analysis.electricityWarnings.map((item: Row) => <div className="p-5" key={item.id}><b className="text-sm text-slate-900">{item.tenant} · {item.location}</b><p className="mt-1 text-sm text-orange-800">{item.explanation}</p></div>)}</div></Panel>}<Panel title="12-month electricity trend" subtitle="Usage is shown by billing interval; skipped periods are not called one-month usage"><TrendChart rows={analysis.electricity} series={[{ key: "billed", label: "Billed", color: "bg-blue-500" }, { key: "paid", label: "Paid", color: "bg-emerald-500" }]} /></Panel><Panel title="Reading coverage"><DataRows columns={["Month", "Readings", "Units", "Billed", "Paid"]} rows={analysis.electricity.slice().reverse().map((row: Row) => [formatMonth(row.month), row.readings, row.units.toLocaleString("en-IN"), money(row.billed), money(row.paid)])} empty="No electricity history is available." /></Panel></TabsContent>
      <TabsContent value="expenses" className="mt-5 space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Summary label="Expenses incurred" value={money(analysis.incurredExpenses)} /><Summary label="Expenses paid" value={money(analysis.paidExpenses)} /><Summary label="Operating cash surplus" value={money(analysis.cashSurplus)} note="Rental cash received minus operating expenses paid" /></div><Panel title="Cash movement" subtitle="Cash-based view; refundable deposits are excluded"><TrendChart rows={analysis.trends.slice(-6)} series={[{ key: "received", label: "Rental cash received", color: "bg-emerald-500" }, { key: "expensesPaid", label: "Operating expenses paid", color: "bg-red-400" }]} /></Panel><div className="flex flex-wrap gap-2"><Button onClick={() => open("expense")}><Plus /> Record expense</Button><Button variant="outline" onClick={() => runAction("generate_recurring_expenses", { billingMonth: month }, "Recurring expenses generated")}>Generate recurring expenses</Button><Button variant="outline" onClick={() => go("expenses")}>Open expense ledger</Button></div></TabsContent>
    </Tabs>
  </div>;
}

function MetricButton({ label: text, value, icon: Icon, positive, warning, onClick }: any) { return <button onClick={onClick} className="min-h-28 rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30"><span className={`grid size-9 place-items-center rounded-xl ${positive ? "bg-emerald-50 text-emerald-700" : warning ? "bg-orange-50 text-orange-700" : "bg-violet-50 text-primary"}`}><Icon className="size-4" /></span><span className="mt-3 block text-xs font-bold uppercase tracking-wide text-slate-500">{text}</span><strong className="mt-1 block truncate text-xl text-slate-900">{value}</strong></button>; }
function Summary({ label: text, value, note }: any) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-sm text-slate-500">{text}</p><strong className="mt-1 block text-2xl text-slate-900">{value}</strong>{note && <p className="mt-1 text-xs text-slate-500">{note}</p>}</div>; }
function Panel({ title, subtitle, children }: any) { return <section className="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-100 p-5"><h3 className="font-bold text-slate-900">{title}</h3>{subtitle && <p className="mt-1 text-sm text-slate-500">{subtitle}</p>}</header>{children}</section>; }
function Empty({ text }: { text: string }) { return <div className="p-6 text-center text-sm text-slate-500">{text}</div>; }
function DataRows({ columns, rows, empty }: any) { if (!rows.length) return <Empty text={empty} />; return <div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{columns.map((column: string) => <th className="px-4 py-3" key={column}>{column}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row: any[], index: number) => <tr key={index}>{row.map((cell, cellIndex) => <td className="px-4 py-3 text-slate-700" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>; }
function TrendChart({ rows, series }: any) { const max = Math.max(...rows.flatMap((row: Row) => series.map((item: Row) => Number(row[item.key]) || 0)), 1); return <div className="p-5"><div className="mb-5 flex flex-wrap gap-4">{series.map((item: Row) => <span key={item.key} className="flex items-center gap-2 text-xs text-slate-600"><i className={`size-2.5 rounded-full ${item.color}`} />{item.label}</span>)}</div><div className="flex min-h-52 items-end gap-2 overflow-x-auto pb-1">{rows.map((row: Row) => <div className="flex min-w-12 flex-1 flex-col items-center gap-2" key={row.month}><div className="flex h-40 w-full items-end justify-center gap-1">{series.map((item: Row) => <div title={`${item.label}: ${money(row[item.key])}`} key={item.key} className={`w-2.5 min-w-2 rounded-t ${item.color}`} style={{ height: `${Math.max(2, Math.round((Number(row[item.key]) || 0) / max * 100))}%` }} />)}</div><span className="whitespace-nowrap text-[11px] text-slate-500">{shortMonth(row.month)}</span></div>)}</div></div>; }
function Bar({ label: text, value, max, moneyValue }: any) { const width = max ? Math.max(1, Math.round(value / max * 100)) : 0; return <div><div className="mb-1.5 flex justify-between gap-3 text-sm"><span className="text-slate-600">{text}</span><b>{moneyValue ? money(value) : value}</b></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-violet-500" style={{ width: `${width}%` }} /></div></div>; }
function money(paise: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: Number(paise) % 100 ? 2 : 0 }).format((Number(paise) || 0) / 100); }
function formatMonth(month: string) { return new Intl.DateTimeFormat("en-IN", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${month}-01T00:00:00Z`)); }
function shortMonth(month: string) { return new Intl.DateTimeFormat("en-IN", { month: "short", timeZone: "UTC" }).format(new Date(`${month}-01T00:00:00Z`)); }
function formatDate(date: string) { return new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T00:00:00Z`)); }
function label(value: string) { return String(value || "unknown").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
