import { calculateMonthlyRent, endOfMonth } from "./rent-calculations.ts";

type Row = Record<string, any>;
type Data = Record<string, any>;

export function buildDashboardAnalysis(data: Data, month: string, propertyFilter = "") {
  const monthStart = `${month}-01`;
  const monthEnd = endOfMonth(month);
  const tenancyById = Object.fromEntries(data.tenancies.map((row: Row) => [row.id, row]));
  const tenantById = Object.fromEntries(data.tenants.map((row: Row) => [row.id, row]));
  const roomById = Object.fromEntries(data.rooms.map((row: Row) => [row.id, row]));
  const propertyById = Object.fromEntries(data.properties.map((row: Row) => [row.id, row]));
  const inProperty = (tenancyId: string) => !propertyFilter || tenancyById[tenancyId]?.property_id === propertyFilter;
  const periodTenancies = data.tenancies.filter((tenancy: Row) => inProperty(tenancy.id) && tenancy.rent_start_date <= monthEnd && (!tenancy.move_out_date || tenancy.move_out_date >= monthStart));
  const allocationsByCharge: Row = {};
  const allocationsByPayment: Row = {};
  data.allocations.filter((allocation: Row) => !allocation.reversed).forEach((allocation: Row) => {
    allocationsByCharge[`${allocation.charge_type}:${allocation.charge_id}`] = (allocationsByCharge[`${allocation.charge_type}:${allocation.charge_id}`] || 0) + Number(allocation.amount_paise);
    allocationsByPayment[allocation.payment_id] = (allocationsByPayment[allocation.payment_id] || 0) + Number(allocation.amount_paise);
  });

  const expectedRent = periodTenancies.reduce((sum: number, tenancy: Row) => sum + (calculateMonthlyRent(tenancy as any, data.rentRateHistory, month)?.amountPaise || 0), 0);
  const selectedRentCharges = data.rentCharges.filter((charge: Row) => !charge.reversed && charge.billing_month === month && inProperty(charge.tenancy_id));
  const billedRent = selectedRentCharges.reduce((sum: number, charge: Row) => sum + Number(charge.amount_paise), 0);
  const paymentsReceived = data.payments.filter((payment: Row) => payment.status === "recorded" && payment.payment_date >= monthStart && payment.payment_date <= monthEnd && inProperty(payment.tenancy_id)).reduce((sum: number, payment: Row) => sum + Number(payment.amount_paise), 0);
  const collectionsAgainstBills = selectedRentCharges.reduce((sum: number, charge: Row) => sum + (allocationsByCharge[`rent:${charge.id}`] || 0), 0)
    + data.electricityBills.filter((bill: Row) => !bill.reversed && bill.billing_month === month && inProperty(bill.tenancy_id)).reduce((sum: number, bill: Row) => sum + (allocationsByCharge[`electricity:${bill.id}`] || 0), 0)
    + data.otherCharges.filter((charge: Row) => !charge.reversed && charge.amount_paise > 0 && charge.charge_date.startsWith(month) && inProperty(charge.tenancy_id)).reduce((sum: number, charge: Row) => sum + (allocationsByCharge[`other:${charge.id}`] || 0), 0);

  const charges = chargeRows(data, allocationsByCharge).filter((charge) => inProperty(charge.tenancyId));
  applyLedgerCredits(charges, data.otherCharges.filter((charge: Row) => !charge.reversed && charge.amount_paise < 0 && inProperty(charge.tenancy_id)));
  const outstanding = charges.reduce((sum, charge) => sum + charge.balance, 0);
  const unappliedCredit = data.payments.filter((payment: Row) => payment.status === "recorded" && inProperty(payment.tenancy_id)).reduce((sum: number, payment: Row) => sum + Math.max(0, Number(payment.amount_paise) - (allocationsByPayment[payment.id] || 0)), 0);
  const depositsHeld = data.deposits.filter((entry: Row) => inProperty(entry.tenancy_id)).reduce((sum: number, entry: Row) => sum + (["received", "adjustment"].includes(entry.type) ? Number(entry.amount_paise) : -Number(entry.amount_paise)), 0);
  const electricityBilled = data.electricityBills.filter((bill: Row) => !bill.reversed && bill.billing_month === month && inProperty(bill.tenancy_id)).reduce((sum: number, bill: Row) => sum + Number(bill.total_paise), 0);
  const incurredExpenses = (data.expenses || []).filter((expense: Row) => (!propertyFilter || expense.property_id === propertyFilter) && expense.incurred_date.startsWith(month)).reduce((sum: number, expense: Row) => sum + Number(expense.amount_paise), 0);
  const paidExpenses = (data.expenses || []).filter((expense: Row) => (!propertyFilter || expense.property_id === propertyFilter) && expense.payment_status === "paid" && expense.paid_date?.startsWith(month)).reduce((sum: number, expense: Row) => sum + Number(expense.amount_paise), 0);
  const activeRooms = data.rooms.filter((room: Row) => room.active && (!propertyFilter || room.property_id === propertyFilter));
  const occupiedRoomIds = new Set(periodTenancies.map((tenancy: Row) => tenancy.room_id));
  const occupancy = { occupied: activeRooms.filter((room: Row) => occupiedRoomIds.has(room.id)).length, total: activeRooms.length };

  const missingRent = periodTenancies.filter((tenancy: Row) => !selectedRentCharges.some((charge: Row) => charge.tenancy_id === tenancy.id));
  const missingReadings = periodTenancies.filter((tenancy: Row) => !(data.electricityReadings || []).some((reading: Row) => reading.tenancy_id === tenancy.id && reading.billing_month === month));
  const draftReadings = (data.electricityReadings || []).filter((reading: Row) => reading.billing_month === month && reading.status === "draft" && inProperty(reading.tenancy_id));
  const overdueCharges = charges.filter((charge) => charge.balance > 0 && charge.dueDate < isoToday());
  const depositShortfalls = data.tenancies.filter((tenancy: Row) => ["active", "notice"].includes(tenancy.status) && inProperty(tenancy.id)).filter((tenancy: Row) => depositForTenancy(data.deposits, tenancy.id) < Number(tenancy.security_deposit_required_paise || 0));
  const followUpsDue = (data.followUps || []).filter((item: Row) => item.status === "open" && item.next_follow_up_date && item.next_follow_up_date <= isoToday() && (!propertyFilter || tenancyById[item.tenancy_id]?.property_id === propertyFilter));
  const maintenanceDue = (data.maintenanceIssues || []).filter((item: Row) => ["open", "in_progress"].includes(item.status) && (!propertyFilter || item.property_id === propertyFilter) && (item.priority === "urgent" || (item.due_date && item.due_date < isoToday())));

  const attention = [
    { type: "overdue", label: "Overdue balances", count: overdueCharges.length, amount: overdueCharges.reduce((sum, charge) => sum + charge.balance, 0), page: "rent" },
    { type: "rent", label: "Rent charges not generated", count: missingRent.length, page: "rent" },
    { type: "reading", label: "Meter readings missing", count: missingReadings.length, page: "electricity" },
    { type: "draft", label: "Draft electricity bills", count: draftReadings.length, page: "electricity" },
    { type: "deposit", label: "Deposit shortfalls", count: depositShortfalls.length, page: "tenants" },
    { type: "followup", label: "Tenant follow-ups due", count: followUpsDue.length, action: "followup" },
    { type: "maintenance", label: "Maintenance needs attention", count: maintenanceDue.length, page: "maintenance" },
  ].filter((item) => item.count > 0);

  const trends = previousMonths(month, 12).map((trendMonth) => monthMetrics(data, trendMonth, propertyFilter, allocationsByCharge, allocationsByPayment));
  const ageing = ageingBuckets(overdueCharges.concat(charges.filter((charge) => charge.balance > 0 && charge.dueDate >= isoToday())));
  const properties = data.properties.filter((property: Row) => property.active && (!propertyFilter || property.id === propertyFilter)).map((property: Row) => propertyMetrics(data, property, month, allocationsByCharge, allocationsByPayment));
  const electricity = previousMonths(month, 12).map((trendMonth) => electricityMetrics(data, trendMonth, propertyFilter, allocationsByCharge));
  const electricityWarnings = unusualElectricity(data, month, propertyFilter, tenancyById, tenantById, roomById, propertyById);
  const upcoming = upcomingItems(data, propertyFilter, tenancyById, tenantById, roomById, propertyById);
  const tenantDues = tenantDueRows(charges, data, tenancyById, tenantById, roomById, propertyById);

  return { expectedRent, billedRent, paymentsReceived, collectionsAgainstBills, outstanding, unappliedCredit, depositsHeld, electricityBilled, incurredExpenses, paidExpenses, cashSurplus: paymentsReceived - paidExpenses, occupancy, attention, trends, ageing, properties, electricity, electricityWarnings, upcoming, tenantDues, allocationsByCharge, allocationsByPayment };
}

function chargeRows(data: Data, allocations: Row) {
  const rows: { id: string; type: string; tenancyId: string; amount: number; balance: number; dueDate: string; month: string }[] = [];
  data.rentCharges.filter((charge: Row) => !charge.reversed).forEach((charge: Row) => rows.push(makeCharge("rent", charge.id, charge.tenancy_id, charge.amount_paise, charge.due_date, charge.billing_month, allocations)));
  data.electricityBills.filter((bill: Row) => !bill.reversed).forEach((bill: Row) => rows.push(makeCharge("electricity", bill.id, bill.tenancy_id, bill.total_paise, bill.due_date || `${bill.billing_month}-28`, bill.billing_month, allocations)));
  data.otherCharges.filter((charge: Row) => !charge.reversed && charge.amount_paise > 0).forEach((charge: Row) => rows.push(makeCharge("other", charge.id, charge.tenancy_id, charge.amount_paise, charge.charge_date, charge.charge_date.slice(0, 7), allocations)));
  return rows;
}

function makeCharge(type: string, id: string, tenancyId: string, amount: number, dueDate: string, month: string, allocations: Row) { return { id, type, tenancyId, amount: Number(amount), balance: Math.max(0, Number(amount) - (allocations[`${type}:${id}`] || 0)), dueDate, month }; }
function applyLedgerCredits(charges: ReturnType<typeof chargeRows>, credits: Row[]) { const byTenancy: Row = {}; credits.forEach((credit) => byTenancy[credit.tenancy_id] = (byTenancy[credit.tenancy_id] || 0) + Math.abs(Number(credit.amount_paise))); Object.entries(byTenancy).forEach(([tenancyId, amount]) => { let remaining = Number(amount); charges.filter((charge) => charge.tenancyId === tenancyId && charge.balance > 0).sort((a, b) => a.dueDate.localeCompare(b.dueDate)).forEach((charge) => { const applied = Math.min(remaining, charge.balance); charge.balance -= applied; remaining -= applied; }); }); }
function depositForTenancy(entries: Row[], tenancyId: string) { return entries.filter((entry) => entry.tenancy_id === tenancyId).reduce((sum, entry) => sum + (["received", "adjustment"].includes(entry.type) ? Number(entry.amount_paise) : -Number(entry.amount_paise)), 0); }

function monthMetrics(data: Data, month: string, propertyFilter: string, allocations: Row, allocationsByPayment: Row) {
  const tenancyById = Object.fromEntries(data.tenancies.map((row: Row) => [row.id, row])); const scoped = (id: string) => !propertyFilter || tenancyById[id]?.property_id === propertyFilter; const start = `${month}-01`; const end = endOfMonth(month);
  const expected = data.tenancies.filter((tenancy: Row) => scoped(tenancy.id) && tenancy.rent_start_date <= end && (!tenancy.move_out_date || tenancy.move_out_date >= start)).reduce((sum: number, tenancy: Row) => sum + (calculateMonthlyRent(tenancy as any, data.rentRateHistory, month)?.amountPaise || 0), 0);
  const rent = data.rentCharges.filter((charge: Row) => !charge.reversed && charge.billing_month === month && scoped(charge.tenancy_id)); const electricity = data.electricityBills.filter((bill: Row) => !bill.reversed && bill.billing_month === month && scoped(bill.tenancy_id)); const other = data.otherCharges.filter((charge: Row) => !charge.reversed && charge.amount_paise > 0 && charge.charge_date.startsWith(month) && scoped(charge.tenancy_id));
  const billed = [...rent, ...electricity, ...other].reduce((sum: number, row: Row) => sum + Number(row.amount_paise ?? row.total_paise), 0); const collected = rent.reduce((sum: number, row: Row) => sum + (allocations[`rent:${row.id}`] || 0), 0) + electricity.reduce((sum: number, row: Row) => sum + (allocations[`electricity:${row.id}`] || 0), 0) + other.reduce((sum: number, row: Row) => sum + (allocations[`other:${row.id}`] || 0), 0);
  const received = data.payments.filter((payment: Row) => payment.status === "recorded" && payment.payment_date >= start && payment.payment_date <= end && scoped(payment.tenancy_id)).reduce((sum: number, payment: Row) => sum + Number(payment.amount_paise), 0); const expensesPaid = (data.expenses || []).filter((expense: Row) => expense.payment_status === "paid" && expense.paid_date?.startsWith(month) && (!propertyFilter || expense.property_id === propertyFilter)).reduce((sum: number, expense: Row) => sum + Number(expense.amount_paise), 0);
  return { month, expected, billed, collected, received, expensesPaid };
}

function ageingBuckets(charges: { balance: number; dueDate: string }[]) { const buckets = [{ label: "Not due", min: -Infinity, max: -1, value: 0 }, { label: "1–30 days", min: 0, max: 30, value: 0 }, { label: "31–60 days", min: 31, max: 60, value: 0 }, { label: "61–90 days", min: 61, max: 90, value: 0 }, { label: "90+ days", min: 91, max: Infinity, value: 0 }]; for (const charge of charges) { const days = Math.floor((Date.parse(`${isoToday()}T00:00:00Z`) - Date.parse(`${charge.dueDate}T00:00:00Z`)) / 86400000); const bucket = buckets.find((item) => days >= item.min && days <= item.max); if (bucket) bucket.value += charge.balance; } return buckets; }

function propertyMetrics(data: Data, property: Row, month: string, allocations: Row, allocationsByPayment: Row) { const tenancyIds = new Set(data.tenancies.filter((tenancy: Row) => tenancy.property_id === property.id).map((tenancy: Row) => tenancy.id)); const metrics = monthMetrics(data, month, property.id, allocations, allocationsByPayment); const charges = chargeRows(data, allocations).filter((charge) => tenancyIds.has(charge.tenancyId)); applyLedgerCredits(charges, data.otherCharges.filter((charge: Row) => !charge.reversed && charge.amount_paise < 0 && tenancyIds.has(charge.tenancy_id))); const rooms = data.rooms.filter((room: Row) => room.active && room.property_id === property.id); const monthStart = `${month}-01`; const monthEnd = endOfMonth(month); const occupied = new Set(data.tenancies.filter((tenancy: Row) => tenancy.property_id === property.id && tenancy.rent_start_date <= monthEnd && (!tenancy.move_out_date || tenancy.move_out_date >= monthStart)).map((tenancy: Row) => tenancy.room_id)).size; const expenses = (data.expenses || []).filter((expense: Row) => expense.property_id === property.id && expense.incurred_date.startsWith(month)).reduce((sum: number, expense: Row) => sum + Number(expense.amount_paise), 0); const availability = availabilityMetrics(data, rooms, monthStart, monthEnd); const completed = data.tenancies.filter((tenancy: Row) => tenancy.property_id === property.id && tenancy.move_out_date); const averageStayDays = completed.length ? Math.round(completed.reduce((sum: number, tenancy: Row) => sum + dateSpan(tenancy.move_in_date, tenancy.move_out_date), 0) / completed.length) : null; const turnover = completed.filter((tenancy: Row) => tenancy.move_out_date.startsWith(month)).length; return { id: property.id, name: property.name, ...metrics, outstanding: charges.reduce((sum, charge) => sum + charge.balance, 0), occupancy: `${occupied}/${rooms.length}`, expenses, ...availability, turnover, averageStayDays }; }
function electricityMetrics(data: Data, month: string, propertyFilter: string, allocations: Row) { const tenancyById = Object.fromEntries(data.tenancies.map((row: Row) => [row.id, row])); const bills = data.electricityBills.filter((bill: Row) => !bill.reversed && bill.billing_month === month && (!propertyFilter || tenancyById[bill.tenancy_id]?.property_id === propertyFilter)); const readings = data.electricityReadings.filter((reading: Row) => reading.billing_month === month && (!propertyFilter || tenancyById[reading.tenancy_id]?.property_id === propertyFilter)); return { month, units: readings.reduce((sum: number, reading: Row) => sum + Number(reading.units), 0), billed: bills.reduce((sum: number, bill: Row) => sum + Number(bill.total_paise), 0), paid: bills.reduce((sum: number, bill: Row) => sum + (allocations[`electricity:${bill.id}`] || 0), 0), readings: readings.length }; }

function availabilityMetrics(data: Data, rooms: Row[], start: string, end: string) { let occupiedDays = 0; let vacantDays = 0; let vacancyLossEstimate = 0; let known = rooms.length > 0; for (const room of rooms) { const history = (data.roomAvailability || []).filter((item: Row) => item.room_id === room.id && item.effective_from <= end && (!item.effective_to || item.effective_to >= start)); if (!history.length) { known = false; continue; } for (const item of history) { const days = overlapDays(start, end, item.effective_from, item.effective_to || end); if (item.status === "occupied") occupiedDays += days; if (item.status === "vacant") { vacantDays += days; if (Number(room.asking_rent_paise) > 0) vacancyLossEstimate += Math.round(Number(room.asking_rent_paise) * days / Number(end.slice(-2))); } } } return { availabilityKnown: known, occupiedDays, vacantDays, vacancyLossEstimate }; }
function unusualElectricity(data: Data, month: string, propertyFilter: string, tenancyById: Row, tenantById: Row, roomById: Row, propertyById: Row) { const output: Row[] = []; const current = (data.electricityReadings || []).filter((reading: Row) => reading.billing_month === month && (!propertyFilter || tenancyById[reading.tenancy_id]?.property_id === propertyFilter)); for (const reading of current) { const history = data.electricityReadings.filter((item: Row) => item.tenancy_id === reading.tenancy_id && item.reading_date < reading.reading_date).sort((a: Row, b: Row) => String(b.reading_date).localeCompare(String(a.reading_date))).slice(0, 4); if (!history.length) continue; const previousDate = history[0].reading_date; const intervalDays = Math.max(1, dateSpan(previousDate, reading.reading_date) - 1); const daily = Number(reading.units) / intervalDays; const baselines = history.map((item: Row, index: number) => { const older = history[index + 1]; const days = older ? Math.max(1, dateSpan(older.reading_date, item.reading_date) - 1) : 30; return Number(item.units) / days; }).filter((value: number) => value > 0).sort((a: number, b: number) => a - b); if (!baselines.length) continue; const baseline = baselines[Math.floor(baselines.length / 2)]; if (daily > baseline * 1.75 && daily - baseline > 0.5) { const tenancy = tenancyById[reading.tenancy_id]; output.push({ id: reading.id, tenant: tenantById[tenancy?.tenant_id]?.full_name || "Tenant", location: `${propertyById[tenancy?.property_id]?.name || "Property"} · Room ${roomById[tenancy?.room_id]?.room_number || "—"}`, daily, baseline, intervalDays, explanation: `${Number(reading.units).toLocaleString("en-IN")} units over ${intervalDays} days (${daily.toFixed(1)}/day), versus a recent median of ${baseline.toFixed(1)}/day.` }); } } return output; }
function overlapDays(startA: string, endA: string, startB: string, endB: string) { const start = startA > startB ? startA : startB; const end = endA < endB ? endA : endB; return start > end ? 0 : dateSpan(start, end); }
function dateSpan(start: string, end: string) { return Math.floor((Date.parse(`${end}T00:00:00Z`) - Date.parse(`${start}T00:00:00Z`)) / 86400000) + 1; }

function upcomingItems(data: Data, propertyFilter: string, tenancyById: Row, tenantById: Row, roomById: Row, propertyById: Row) { const today = isoToday(); const until = addDays(today, 45); const out: Row[] = []; const add = (date: string, type: string, tenancyId: string, detail: string) => { if (date >= today && date <= until && (!propertyFilter || tenancyById[tenancyId]?.property_id === propertyFilter)) { const tenancy = tenancyById[tenancyId]; out.push({ date, type, tenant: tenantById[tenancy?.tenant_id]?.full_name || "Tenant", location: `${propertyById[tenancy?.property_id]?.name || "Property"} · Room ${roomById[tenancy?.room_id]?.room_number || "—"}`, detail }); } }; data.tenancies.forEach((tenancy: Row) => { if (tenancy.planned_move_out_date) add(tenancy.planned_move_out_date, "Move-out", tenancy.id, "Planned move-out"); if (tenancy.agreement_end_date) add(tenancy.agreement_end_date, "Agreement", tenancy.id, "Agreement renewal due"); }); data.rentRateHistory.forEach((rate: Row) => add(rate.effective_from, "Rent rate", rate.tenancy_id, "Scheduled rent change")); return out.sort((a, b) => a.date.localeCompare(b.date)).slice(0, 12); }
function tenantDueRows(charges: ReturnType<typeof chargeRows>, data: Data, tenancyById: Row, tenantById: Row, roomById: Row, propertyById: Row) { const grouped: Row = {}; charges.filter((charge) => charge.balance > 0).forEach((charge) => { const tenancy = tenancyById[charge.tenancyId]; const tenantId = tenancy?.tenant_id; if (!tenantId) return; const row = grouped[tenantId] ||= { tenantId, tenant: tenantById[tenantId]?.full_name || "Tenant", room: roomById[tenancy.room_id]?.room_number || "—", property: propertyById[tenancy.property_id]?.name || "Property", amount: 0, oldestDue: charge.dueDate, status: tenancy.status }; row.amount += charge.balance; if (charge.dueDate < row.oldestDue) row.oldestDue = charge.dueDate; }); return Object.values(grouped).sort((a: any, b: any) => b.amount - a.amount); }
function previousMonths(month: string, count: number) { const [year, value] = month.split("-").map(Number); return Array.from({ length: count }, (_, index) => { const date = new Date(Date.UTC(year, value - count + index, 1)); return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`; }); }
function isoToday() { return new Date().toISOString().slice(0, 10); }
function addDays(date: string, days: number) { const value = new Date(`${date}T00:00:00Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10); }
